# -*- coding: utf-8 -*-
"""Lab2Task.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KSu-qyn8oLJ3Tr5NhPDuGJLC5YQzioRm
"""



"""# Matplotlib

# Numpy

# List
"""

my_list = [1,2,3,4,5,6,7,8,9,10]
print(my_list)

list_sum = sum(my_list)
list_max = max(my_list)
list_min = min(my_list)
my_list.append(11)
print(my_list)

my_list.remove(11)
print(my_list)

my_list.sort()
print(my_list)

my_list.reverse()
print(my_list)

my_list.sort(reverse=True)
print(my_list)


print(f"Sum of the list: {list_sum}")
print(f"Maximum value in the list: {list_max}")
print(f"Minimum value in the list: {list_min}")

"""# Tuple"""

fruit_tuple = ("apple", "banana", "cherry", "date", "Strawberry")
print(fruit_tuple)

print(f"Second element: {fruit_tuple[1]}")
print(f"Last element: {fruit_tuple[-1]}")

my_list = list(fruit_tuple)
my_list[2]='orange'
print(f"Modified list: {my_list}")
fruit_tuple = tuple(my_list)
print(f"Modified tuple: {fruit_tuple}")

"""# Set"""

set1 = {1, 2, 3, 4, 5}
set2 = {4, 5, 6, 7, 8}

print("Set 1:", set1)
print("Set 2:", set2)

union_set = set1.union(set2)
print("Union of Set 1 and Set 2:", union_set)

intersection_set = set1.intersection(set2)
print("Intersection of Set 1 and Set 2:", intersection_set)

difference_set = set1.difference(set2)
print("Difference of Set 1 and Set 2:", difference_set)

set1.add(6)
print("Set 1 after adding 6:", set1)

set1.remove(3)
print("Set 1 after removing 3:", set1)

"""# Dictionary"""

student_marks = {
    "Alice": 85,
    "Bob": 92,
    "Charlie": 78,
    "David": 95,
    "Eve": 88,
     "Eve": 88

}

print(student_marks)

student_marks["Bob"] = 90
print(student_marks)

del student_marks["Charlie"]
print(student_marks)